export default {
  name: 'property',
  title: 'Property',
  type: 'document',
  fields: [
    { name: 'name', title: 'Nombre', type: 'string' },
    {
      name: 'slug',
      title: 'Slug (Tocar en "Generate" después de agregar el nombre)',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 96,
      },
    },
    { name: 'price', title: 'Precio', type: 'number' },
    {
      name: 'currency',
      title: 'Moneda',
      type: 'string',
      options: {
        list: [
          { title: 'Pesos', value: 'Pesos' },
          { title: 'Dolares', value: 'Dolares' },
        ],
      },
    },
    {
      name: 'operationType',
      title: 'Tipo de Operación',
      type: 'string',
      options: {
        list: [
          { title: 'Venta', value: 'Venta' },
          { title: 'Alquiler', value: 'Alquiler' },
          { title: 'Alquiler Temporario', value: 'Alquiler Temporario' },
        ],
      },
    },
    {
      name: 'propertyType',
      title: 'Tipo de propiedad',
      type: 'string',
      options: {
        list: [
          { title: 'Barrio Cerrado', value: 'Barrio Cerrado' },
          { title: 'Campo', value: 'Campo' },
          { title: 'Casa', value: 'Casa' },
          { title: 'Casa Quinta', value: 'Casa Quinta' },
          { title: 'Cochera', value: 'Cochera' },
          { title: 'Country', value: 'Country' },
          { title: 'Club de Campo', value: 'Club de Campo' },
          { title: 'Departamento', value: 'Departamento' },
          { title: 'Departamento', value: 'Departamento' },
          { title: 'Depósito', value: 'Depósito' },
          { title: 'Dúplex', value: 'Dúplex' },
          { title: 'Edificio Comercial', value: 'Edificio Comercial' },
          { title: 'Emprendimiento', value: 'Emprendimiento' },
          { title: 'En Construcción', value: 'En Construcción' },
          { title: 'Fondo de Comercio', value: 'Fondo de Comercio' },
          { title: 'Galpón', value: 'Galpón' },
          { title: 'Hotel', value: 'Hotel' },
          { title: 'Local', value: 'Local' },
          { title: 'Lote', value: 'Lote' },
          { title: 'Oficina', value: 'Oficina' },
          { title: 'Terreno', value: 'Terreno' },
          { title: 'Tríplex', value: 'Tríplex' },
        ],
      },
    },
    { name: 'location', title: 'Ubicación', type: 'string' },
    { name: 'description', title: 'Descripción', type: 'text' },
    { name: 'rooms', title: 'Ambientes', type: 'number', initialValue: 0 },
    { name: 'bathrooms', title: 'Baños', type: 'number', initialValue: 0 },
    { name: 'area', title: 'Superficie', type: 'number', initialValue: 0 },
    { name: 'measure', title: 'Medidas', type: 'string', initialValue: '0x0' },
    { name: 'garage', title: 'Garage', type: 'boolean', initialValue: false },
    {
      name: 'electricity',
      title: 'Electricidad',
      type: 'boolean',
      initialValue: false,
    },
    { name: 'gas', title: 'Gas', type: 'boolean', initialValue: false },
    { name: 'water', title: 'Agua', type: 'boolean', initialValue: false },
    { name: 'asphalt', title: 'Asfalto', type: 'boolean', initialValue: false },
    { name: 'sewer', title: 'Cloacas', type: 'boolean', initialValue: false },
    { name: 'antiquity', title: 'Antigüedad', type: 'number', initialValue: 0 },
    { name: 'mainImage', title: 'Imagen principal', type: 'image' },
    {
      name: 'images',
      title: 'Otras Imágenes',
      type: 'array',
      of: [{ type: 'image' }],
    },
    {
      name: 'featured',
      title: 'Destacada',
      type: 'boolean',
      initialValue: false,
    },
    { name: 'lat', title: 'Latitud', type: 'number', initialValue: 0 },
    { name: 'lng', title: 'Longitud', type: 'number', initialValue: 0 },
  ],
};
